In [1]:
import pandas as pd
import numpy as np
import pymysql
import sqlalchemy

In [19]:
# extracting data from csv
df = pd.read_csv(r"..\Data\raw_data.csv")
df.rename(columns = {'Customer ID':'CustomerID'}, inplace=True)
print("raw data size: ",df.shape[0])

df = df.drop_duplicates(keep='first')
print("after removing duplicates: ",df.shape[0])

FileNotFoundError: [Errno 2] No such file or directory: '..\\Data\\raw_data\\raw_data.csv'

In [3]:
print(df.isnull().sum())
df

Invoice             0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
Price               0
CustomerID     235151
Country             0
dtype: int64

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

Rows having price=0 are measn item was rotten,damaged, expired, stolen or anything except sold.   
They are neither contributing in revenue nor useful for RFM analysis of customer.   
so delete price=0

In [4]:
# removing rows where price is 0

df = df[df.Price>0]

cleaning description column and stock code column

In [5]:
# extracting character containing stock code

import re

# finding rows containing character in stockcode to get unusual stock code and discription

df['StockCode'] =  df['StockCode'].astype(str).str.strip().str.upper()
df['Description'] =  df['Description'].astype(str).str.strip().str.upper()
special_stock = df[df['StockCode'].astype(str).str.contains(r'\b\D+', na=False)]
special_stock[['StockCode','Description']].value_counts()

StockCode     Description
POST          POSTAGE                                2079
DOT           DOTCOM POSTAGE                         1418
M             MANUAL                                 1385
C2            CARRIAGE                                274
D             DISCOUNT                                173
S             SAMPLES                                 101
BANK CHARGES  BANK CHARGES                            100
ADJUST        ADJUSTMENT BY JOHN ON 26/01/2010 16      38
AMAZONFEE     AMAZON FEE                               36
DCGS0058      MISO PRETTY  GUM                         30
GIFT_0001_20  DOTCOMGIFTSHOP GIFT VOUCHER £20.00       26
ADJUST        ADJUSTMENT BY JOHN ON 26/01/2010 17      26
GIFT_0001_30  DOTCOMGIFTSHOP GIFT VOUCHER £30.00       24
DCGSSGIRL     GIRLS PARTY BAG                          23
DCGSSBOY      BOYS PARTY BAG                           21
PADS          PADS TO MATCH ALL CUSHIONS               18
CRUK          CRUK COMMISSION                          16
DCGS0076      SUNJAR LED NIGHT NIGHT LIGHT             14
GIFT_0001_10  DOTCOMGIFTSHOP GIFT VOUCHER £10.00       14
DCGS0003      BOXED GLASS ASHTRAY                      13
TEST001       THIS IS A TEST PRODUCT.                  13
GIFT_0001_50  DOTCOMGIFTSHOP GIFT VOUCHER £50.00        6
DCGS0069      OOH LA LA DOGS COLLAR                     5
GIFT_0001_40  DOTCOMGIFTSHOP GIFT VOUCHER £40.00        5
DCGS0004      HAYNES CAMPER SHOULDER BAG                4
DCGS0072      CAT CAMOUFLAGUE COLLAR                    3
ADJUST        ADJUSTMENT BY PETER ON 24/05/2010 1       3
ADJUST2       ADJUSTMENT BY PETER ON JUN 25 2010        3
DCGS0068      DOGS NIGHT COLLAR                         2
GIFT_0001_80  DOTCOMGIFTSHOP GIFT VOUCHER £80.00        2
DCGS0066N     NAVY CUDDLES DOG HOODIE                   2
DCGS0070      CAMOUFLAGE DOG COLLAR                     2
SP1002        KID'S CHALKBOARD/EASEL                    2
DCGS0044      HANDZ-OFF CAR FRESHENER                   1
TEST002       THIS IS A TEST PRODUCT.                   1
DCGS0075      CAMOUFLAGUE DOG LEAD                      1
DCGS0041      HAYNES MINI-COOPER PLAYING CARDS          1
GIFT_0001_70  DOTCOMGIFTSHOP GIFT VOUCHER £70.00        1
DCGS0037      KEY-RING CORKSCREW                        1
DCGS0062      ROAD-RAGE CAR FRESHENER                   1
B             ADJUST BAD DEBT                           1
Name: count, dtype: int64

In [6]:
# cleaning description column
size_before_del = df.shape[0]
to_del_desc = ['EBAY','UPDATE', 'FOUND', 'CHECK', 'ADJUSTMENT', 'AMAZON']
audit_keywords = ['SOLD AS', 'CODE MIX UP', 'WRONG CODE', 'HISTORIC COMPUTER', 'INVCD AS']
junk_keywords = [ 'MISSING', r'\bWET\b', '\bRUSTY\b', r'\bROT\b', '\bSMASH\b', 'DAMAGE', 'THROWN AWAY', 'UNSALEABLE', r'^\?+' ,
                  r'\bLOST\b', 'WRONGLY MARKED', 'DESTROYED', r'\bFOUND', 'STOCK CHECK', 'PUT ASIDE', 'CRUSHED']
mixed_keyword = [
    r'^\d+[A-Z]?\s+MIXED$',  # '85123A MIXED', '21733 MIXED'
    r'\bMIXED WITH\b',  
    r'\bMIXED UP\b',  
]
df['to_delete'] = (
                    df['Description'].isin(to_del_desc) |  df['Description'].str.contains('|'.join(audit_keywords)) |
                     df['Description'].str.contains('|'.join(junk_keywords)) | df['Description'].str.contains('|'.join(mixed_keyword))
                )
print("description getting deleted are:")
print( df[df['to_delete']]['Description'].unique().tolist() )
df = df[~df['to_delete']]

# cleaning stock code column
to_del_stock = [ 'POST', 'DOT', 'M', 'D', 'C2', 'S', 'BANK CHARGES', 'AMAZONFEE', 'CRUK', 'B',]
to_del_stock_contains = ['GIFT','TEST','ADJUST']
df['to_delete'] = ( df['StockCode'].isin(to_del_stock) | df['StockCode'].str.contains('|'.join(to_del_stock_contains)) )
print("stock code getting delete are-")
print( df[df['to_delete']]['Description'].unique() )
df = df[~df['to_delete']]

print('delete rows counts', size_before_del-df.shape[0])
df.drop(columns=['to_delete'], inplace=True)

description getting deleted are:
[]
stock code getting delete are-
<ArrowStringArray>
[                            'POSTAGE',                            'DISCOUNT',
                      'DOTCOM POSTAGE',                              'MANUAL',
                            'CARRIAGE',                        'BANK CHARGES',
             'THIS IS A TEST PRODUCT.',  'DOTCOMGIFTSHOP GIFT VOUCHER £80.00',
  'DOTCOMGIFTSHOP GIFT VOUCHER £20.00',  'DOTCOMGIFTSHOP GIFT VOUCHER £10.00',
  'DOTCOMGIFTSHOP GIFT VOUCHER £50.00',  'DOTCOMGIFTSHOP GIFT VOUCHER £30.00',
 'ADJUSTMENT BY JOHN ON 26/01/2010 16', 'ADJUSTMENT BY JOHN ON 26/01/2010 17',
                             'SAMPLES', 'ADJUSTMENT BY PETER ON 24/05/2010 1',
  'DOTCOMGIFTSHOP GIFT VOUCHER £70.00',  'ADJUSTMENT BY PETER ON JUN 25 2010',
  'DOTCOMGIFTSHOP GIFT VOUCHER £40.00',                          'AMAZON FEE',
                     'ADJUST BAD DEBT',                     'CRUK COMMISSION']
Length: 22, dtype: str
delete rows counts 5745

now cleaning invoice column by following same procedure of extracting character containing rows

In [7]:
df[df.Invoice.str.contains(r'\D')]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
1065909,C581490,22178,VICTORIAN GLASS HANGING T-LIGHT,-12,2011-12-09 09:57:00,1.95,14397.0,United Kingdom
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [8]:
# deleting cancelled order along with matching original order


# creating a abosolute quantity column
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Abs_Quantity'] = df['Quantity'].abs()

# Separate into Positive Orders and Negative Cancellations
pos_df = df[df['Quantity'] > 0].copy()
neg_df = df[df['Quantity'] < 0].copy()

# Perform inner join while keeping index values
merged = pd.merge(
    pos_df.reset_index(), 
    neg_df.reset_index(), 
    on=['CustomerID', 'StockCode', 'Price', 'Abs_Quantity'],
    suffixes=('_orig', '_cancel')
)
# matching cancellation with exact original order
valid_pairs = merged[merged['InvoiceDate_cancel'] >= merged['InvoiceDate_orig']]
valid_pairs['Time_Diff'] = valid_pairs['InvoiceDate_cancel'] - valid_pairs['InvoiceDate_orig']
valid_pairs = valid_pairs.sort_values(by='Time_Diff', ascending=True)
valid_pairs = valid_pairs.drop_duplicates(subset=['index_cancel'], keep='first')
valid_pairs = valid_pairs.drop_duplicates(subset=['index_orig'], keep='first')

# 6. Extract all row indices that belong to cancellation pairs
indices_to_drop = set(valid_pairs['index_orig']).union(set(valid_pairs['index_cancel']))

# 7. Filter the original DataFrame to keep only non-cancelled data
df = df[~df.index.isin(indices_to_drop)].drop(columns=['Abs_Quantity'])
rows = df.shape[0]
df = df[~ df.Invoice.str.contains(r'\D')]
print(f"Removed- {len(valid_pairs)} canceled pairs and {rows-df.shape[0]} unpaired canceled order.")

Removed- 6235 canceled pairs and 11680 unpaired canceled order.

cleaning quantity, invoice date, country

In [9]:
# cleaning quantity column

df = df[df.Quantity>0]

In [10]:
# cleanign invoice date column
# correct data type, no null values, should be between 1 dec 2009 to 1 dec 2011 , in working time hours

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print('start date ', df.InvoiceDate.min() )
print('end date ', df.InvoiceDate.max() )

df['Hour'] = df['InvoiceDate'].dt.hour
df['Minute'] = df['InvoiceDate'].dt.minute
print('\n', df[['InvoiceDate', 'Hour', 'Minute']].sort_values(by=['Hour','Minute']) )

df = df.drop( columns = ['Hour','Minute'] )

start date  2009-12-01 07:45:00
end date  2011-12-09 12:50:00

                InvoiceDate  Hour  Minute
830128 2011-08-18 06:20:00     6      20
19714  2009-12-09 07:01:00     7       1
19715  2009-12-09 07:01:00     7       1
19716  2009-12-09 07:01:00     7       1
19717  2009-12-09 07:01:00     7       1
...                    ...   ...     ...
350033 2010-09-21 20:38:00    20      38
350034 2010-09-21 20:38:00    20      38
350035 2010-09-21 20:38:00    20      38
350036 2010-09-21 20:38:00    20      38
350037 2010-09-21 20:38:00    20      38

[997122 rows x 3 columns]

In [11]:
#  cleaning country column

df['Country'] = df.Country.str.title()

df['Country'].unique()

<ArrowStringArray>
[      'United Kingdom',               'France',            'Australia',
                 'Eire',              'Germany',             'Portugal',
              'Denmark',          'Netherlands',               'Poland',
      'Channel Islands',                'Spain',               'Cyprus',
              'Belgium',               'Greece',               'Norway',
              'Austria',               'Sweden', 'United Arab Emirates',
              'Finland',                'Italy',          'Switzerland',
                  'Usa',          'Unspecified',                'Japan',
                'Malta',              'Bahrain',                  'Rsa',
              'Bermuda',            'Hong Kong',            'Singapore',
             'Thailand',               'Israel',            'Lithuania',
              'Nigeria',          'West Indies',              'Lebanon',
               'Brazil',               'Canada',              'Iceland',
                'Korea',         'Saudi Arabia',       'Czech Republic',
   'European Community']
Length: 43, dtype: str

cleaning customer id column

There are large(200k+) number of null customerid after removing them output will be affected by approx 20% so handle them differently

In [12]:
# Create unique customer IDs for null IDs e.g. Guest_Invoice 


df.columns=['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'CustomerID', 'Country']

df['CustomerID'] = np.where(
    df['CustomerID'].isna(), 
    'Guest_' + df['Invoice'].astype(str),
    df['CustomerID'].astype('Int64').astype(str)
)

# df['Total_Amount'] = np.round(df['Quantity']*df['Price'],2)
df.reset_index(drop=True, inplace=True)

In [13]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
CustomerID     0
Country        0
dtype: int64

In [14]:
#  some stock code are associated with multiple similar descriptions

dim_product = (
    df.groupby('StockCode')['Description']
    .agg(lambda x: x.mode()[0])
    .reset_index()
)

df['Description'] = df['StockCode'].map(dim_product.set_index('StockCode')['Description'])

In [15]:
# save cleaned data into csv

# df.to_csv(r'C:\Users\hp\Downloads\E-Commerce-Retention-Engine\Data\processed_data.csv', index=False)

In [16]:
#   dimension and exporting into sql database

# exporting to sql
url = "mysql+pymysql://root:Admin@localhost:3306/ecommerce"
engine = sqlalchemy.create_engine(url)
# dim_product.to_sql('dim_product', con=engine, if_exists='replace', index=False)
# df.to_sql('fact_transactions', con = engine, if_exists = 'replace', index=False)

997122

**Data have been cleaned , saved and exported into sql database**